import {
  Activity,
  Archive,
  AtSign,
  Award,
  BarChart3,
  Blocks,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  Building2,
  CalendarCheck,
  CalendarDays,
  CheckSquare,
  CircleCheckBig,
  ClipboardCheck,
  ClipboardList,
  CloudUpload,
  Code2,
  Compass,
  Component,
  Cpu,
  Crosshair,
  Database,
  DollarSign,
  ExternalLink,
  Factory,
  FileText,
  Filter,
  Flag,
  Flame,
  FolderOpen,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Hash,
  History,
  Hourglass,
  Image as ImageIcon,
  KeyRound,
  Layers,
  Layers3,
  LayoutGrid,
  Leaf,
  Lightbulb,
  LineChart,
  Link2,
  ListChecks,
  LockKeyhole,
  Mail,
  Map as MapIcon,
  MapPin,
  MessageSquare,
  MessagesSquare,
  Microscope,
  Minus,
  Monitor,
  Network,
  Newspaper,
  Orbit,
  PackageOpen,
  Palette,
  Percent,
  PieChart,
  Plus,
  Presentation,
  Puzzle,
  Radar,
  RefreshCw,
  Rocket,
  Route,
  Scale,
  Search,
  ServerCog,
  Share2,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Target,
  TerminalSquare,
  Timer,
  TimerReset,
  TrendingDown,
  TrendingUp,
  Trophy,
  UserCheck,
  UserRound,
  Users,
  Watch,
  Workflow,
  Zap,
} from 'lucide-react'

/**
 * The icons a slide can carry — the same curated set the backend offers the
 * model, imported by name rather than `import * as` so the bundle only carries
 * these rather than all 2000+ Lucide icons.
 *
 * Kept out of SlideIcon.jsx so that file exports a component and nothing else.
 * Every key was checked against the lucide-react package contents.
 */
export const SLIDE_ICONS = {
  activity: Activity,
  archive: Archive,
  'at-sign': AtSign,
  award: Award,
  'bar-chart-3': BarChart3,
  blocks: Blocks,
  'book-open': BookOpen,
  bookmark: Bookmark,
  bot: Bot,
  box: Box,
  brain: Brain,
  'building-2': Building2,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  'check-square': CheckSquare,
  'circle-check-big': CircleCheckBig,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'cloud-upload': CloudUpload,
  'code-2': Code2,
  compass: Compass,
  component: Component,
  cpu: Cpu,
  crosshair: Crosshair,
  database: Database,
  'dollar-sign': DollarSign,
  'external-link': ExternalLink,
  factory: Factory,
  'file-text': FileText,
  filter: Filter,
  flag: Flag,
  flame: Flame,
  'folder-open': FolderOpen,
  gauge: Gauge,
  'git-branch': GitBranch,
  globe: Globe,
  'graduation-cap': GraduationCap,
  handshake: Handshake,
  hash: Hash,
  history: History,
  hourglass: Hourglass,
  image: ImageIcon,
  'key-round': KeyRound,
  layers: Layers,
  'layers-3': Layers3,
  'layout-grid': LayoutGrid,
  leaf: Leaf,
  lightbulb: Lightbulb,
  'line-chart': LineChart,
  'link-2': Link2,
  'list-checks': ListChecks,
  'lock-keyhole': LockKeyhole,
  mail: Mail,
  map: MapIcon,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  microscope: Microscope,
  minus: Minus,
  monitor: Monitor,
  network: Network,
  newspaper: Newspaper,
  orbit: Orbit,
  'package-open': PackageOpen,
  palette: Palette,
  percent: Percent,
  'pie-chart': PieChart,
  plus: Plus,
  presentation: Presentation,
  puzzle: Puzzle,
  radar: Radar,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  route: Route,
  scale: Scale,
  search: Search,
  'server-cog': ServerCog,
  'share-2': Share2,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  target: Target,
  'terminal-square': TerminalSquare,
  timer: Timer,
  'timer-reset': TimerReset,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  trophy: Trophy,
  'user-check': UserCheck,
  'user-round': UserRound,
  users: Users,
  watch: Watch,
  workflow: Workflow,
  zap: Zap,
}

export const SLIDE_ICON_NAMES = Object.keys(SLIDE_ICONS)
